#!/bin/sh

RUNNER_ETC_DIR=${{{runner_etc_dir}}:-$RELEASE_ROOT_DIR/etc}
RUNNER_SCHEMA_DIR=${{{runner_schema_dir}}:-$RELEASE_ROOT_DIR/schema}
CUTTLEFISHCMD="$ERTS_DIR/bin/escript $RELEASE_ROOT_DIR/bin/cuttlefish"

if CUTTLE_CONF=$($CUTTLEFISHCMD -e $RUNNER_ETC_DIR -d "generated.configs" -s $RUNNER_SCHEMA_DIR -c "$RUNNER_ETC_DIR/{{release_name}}.conf")
then
    CONFIG_PATH=$(echo $CUTTLE_CONF | sed -E 's/.*-config ([^ ]+).*/\1/')
    VMARGS_PATH=$(echo $CUTTLE_CONF | sed -E 's/.*-vm_args ([^ ]+).*/\1/')

    RELX_CONFIG_PATH=releases/{{release_version}}/sys.config
    ln -sf $VMARGS_PATH releases/{{release_version}}/vm.args
    ln -sf $CONFIG_PATH $RELX_CONFIG_PATH
else
    echo "Cuttlefish failed! Oh no!: $CUTTLEFISH_CONFIG"
    exit 1
fi

NODENAME=`egrep '^[ \t]*nodename[ \t]*=[ \t]*' "$RUNNER_ETC_DIR/{{release_name}}.conf" 2> /dev/null | tail -n 1 | cut -d = -f 2`
if [ -z "$NODENAME" ]; then
    echo "vm.args needs to have a -name parameter."
    echo "  -sname is not supported."
    exit 1
else
    NAME_TYPE="-name"    
    NAME="${NODENAME# *}"
    export NAME

    PIPE_DIR="/tmp/erl_pipes/$NAME/"
    mkdir -p "$PIPE_DIR"
    export PIPE_DIR
fi
